# Site
repository: vicky-mao/vicky-mao.github.io
# favicon: images/favicon.ico

# Personal info
name: Vicky Mao
title: Senior Consultant
email: 522631185@qq.com
website: https://vicky-mao.github.io

# Social links
#twitter_username: facespics
#github_username:  sproogen
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: vicky-mao-6ab988138
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi there, my name's Vicky and I'm a senior consultant. Apart from doing consultations for corporate strategy projects I also have got rich experience in laying out strategic plans for infrastructure construction projects. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>Research & Analysis</mark> and <mark>Corporate Strategy</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my career as a corporate strategy consultant, I'm also happy wife of an intelligent man and proud mom of two cute kids. My family is the strongest support behind my success and certainly one of the most important part of my life.

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

